### ISSUE TITLE
Video is fast / sharing image

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/christmas-video-2017#15]
Could we show all the text images on one 'slide' at the end of video or slow things down?

**Comment by tomdyson** [comment]
if we slow it all down the image changes won't sync with the rhythm of the audio. 

having all the text images on one slide at the end would be great though. we should also use this as the sharing image. @tmsndrs do you have time to mock this image up for @tm-kn?

**Comment by tomdyson** [comment]
We'll auto-generate two images: one portrait for the final image of the video, one landscape for use as a sharing image.

**Comment by tmsndrs** [comment]
Thanks. I had a chat with Ben about this. Happy to let others lead. It's looking great though!

**Comment by tomdyson** [comment]
Done in 76a4bc73c786ad614e9c3e771b4fce2a9037bddc
