### ISSUE TITLE
Letters appearing when the shouldn't on non-card images

### ISSUE THREAD

**Issue by tmsndrs** [torchbox/christmas-video-2017#16]
<img width="629" alt="screen shot 2017-12-20 at 13 57 13" src="https://user-images.githubusercontent.com/7290588/34210458-d244e894-e58d-11e7-89ed-5aba25a768e3.png">

**Comment by tombola** [comment]
I got the same one (Tom Williams: R)

**Comment by tombola** [comment]
Also
![screen shot 2017-12-20 at 14 05 01](https://user-images.githubusercontent.com/812348/34210755-e2056ff0-e58e-11e7-8d36-3829b1b4e17b.png)
