### ISSUE TITLE
ffmpeg optimisations

### ISSUE THREAD

**Issue by tomdyson** [torchbox/christmas-video-2017#2]
Notes from Colin on Slack:

- vcodec is not selected in the christmas card ffmpeg command, ffmpeg will auto-select, guess to `libx264` (expect this is printed by ffmpeg when run, or visible if  verbose) (https://github.com/torchbox/christmas-video-2017/blob/master/xmasvideo/convert.py)
- `libx264` doc - https://trac.ffmpeg.org/wiki/Encode/H.264
- with `libx264` there are `-preset` options that affect the compression quality, measured by filesize. setting to `ultrafast` will result in faster output, but a larger filesize. tradeoff of time to disk vs. network speed? 
- with `libx264` is there a `-movflags +faststart` output option that optimise for browsers, moving some information to the beginning of your file and allowing the video to begin playing before it is completely downloaded by the viewer. (edited)

re threads, doc on `libx264` options http://www.mplayerhq.hu/DOCS/HTML/en/menc-feat-x264.html (mplayer uses ffmpeg)  
```threads: This option allows to spawn threads to encode in parallel on multiple CPUs. You can manually select the number of threads to be created or, better, set threads=auto and let x264 detect how many CPUs are available and pick an appropriate number of threads. If you have a multi-processor machine, you should really consider using it as it can to increase encoding speed linearly with the number of CPU cores (about 94% per CPU core), with very little quality reduction (about 0.005dB for dual processor, about 0.01dB for a quad processor machine).```
in examples you see `-threads 0` which must effectively be `threads=auto`(edit: confirmed + default is 0/auto https://ffmpeg.org/ffmpeg-codecs.html) (edited)

e.g. re ffmpeg for streaming https://videoblerg.wordpress.com/2017/11/10/ffmpeg-and-how-to-use-it-wrong/ (edited)

**Comment by tm-kn** [comment]
Thanks. I won't set `threads` if it's set at `auto` by default. `ultrafast` increases the speed a lot, but filesize seems very similar.
